import { Link, createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { Bookmark, Brain, CheckCircle2, Heart, Highlighter, NotebookPen, Plus, Search, Sparkles, Trash2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { loadSavedVerses, removeSavedVerse, type SavedVerse } from "@/lib/app-state";
import { addPersonalPrayer, deletePersonalPrayer, isPrayerAnswered, loadPersonalPrayers, loadPrayerStatuses, setPrayerAnswered, type PersonalPrayer, type PrayerStatus } from "@/lib/prayer-state";
import { askStudyMemoryFn, type StudyMemoryAnswer, type StudyMemorySource } from "@/lib/study-memory.functions";
import { allChapterStudies, allDailyReviews, type ChapterStudy, type DailyReview } from "@/lib/study-state";

export const Route=createFileRoute("/saved")({component:JournalPage});
type Tab="notes"|"verses"|"prayers"|"reviews"|"memory";
type PrayerView={id:string;reference:string;text:string;createdAt:string;personal:boolean};

function JournalPage(){
  const [verses,setVerses]=useState<SavedVerse[]>([]);const [studies,setStudies]=useState<ChapterStudy[]>([]);const [reviews,setReviews]=useState<DailyReview[]>([]);const [personalPrayers,setPersonalPrayers]=useState<PersonalPrayer[]>([]);const [prayerStatuses,setPrayerStatuses]=useState<Record<string,PrayerStatus>>({});const [newPrayer,setNewPrayer]=useState("");const [tab,setTab]=useState<Tab>("notes");const [query,setQuery]=useState("");
  const [memoryQuestion,setMemoryQuestion]=useState("");const [memoryAnswer,setMemoryAnswer]=useState<StudyMemoryAnswer|null>(null);const [memoryMessage,setMemoryMessage]=useState("");const [asking,setAsking]=useState(false);
  const askMemory=useServerFn(askStudyMemoryFn);
  const refresh=()=>{setVerses(loadSavedVerses());setStudies(allChapterStudies());setReviews(allDailyReviews());setPersonalPrayers(loadPersonalPrayers());setPrayerStatuses(loadPrayerStatuses())};
  useEffect(()=>{refresh()},[]);
  const q=query.trim().toLowerCase();
  const filteredVerses=useMemo(()=>verses.filter(v=>!q||`${v.reference} ${v.text} ${v.note??""}`.toLowerCase().includes(q)),[verses,q]);
  const filteredStudies=useMemo(()=>studies.filter(s=>!q||`${s.passage} ${s.intention??""} ${Object.values(s.reflections).join(" ")} ${s.prayer??""}`.toLowerCase().includes(q)),[studies,q]);
  const filteredReviews=useMemo(()=>reviews.filter(r=>!q||`${r.date} ${r.takeaway??""} ${r.gratitude??""} ${r.prayer??""}`.toLowerCase().includes(q)),[reviews,q]);
  const prayers=useMemo<PrayerView[]>(()=>[
    ...personalPrayers.map(p=>({id:p.id,reference:"Personal prayer",text:p.text,createdAt:p.createdAt,personal:true})),
    ...studies.flatMap(s=>s.prayer?.trim()?[{id:`chapter:${s.passage}`,reference:s.passage,text:s.prayer.trim(),createdAt:s.updatedAt,personal:false}]:[]),
    ...reviews.flatMap(r=>r.prayer?.trim()?[{id:`daily:${r.date}`,reference:`Daily review · ${r.date}`,text:r.prayer.trim(),createdAt:r.updatedAt,personal:false}]:[]),
  ].filter(p=>!q||`${p.reference} ${p.text}`.toLowerCase().includes(q)).sort((a,b)=>{const aa=isPrayerAnswered(prayerStatuses[a.id])?1:0;const bb=isPrayerAnswered(prayerStatuses[b.id])?1:0;return aa-bb||b.createdAt.localeCompare(a.createdAt)}),[personalPrayers,studies,reviews,prayerStatuses,q]);
  const memorySources=useMemo<StudyMemorySource[]>(()=>[
    ...studies.flatMap(s=>{const own=[s.intention,s.reflections.observation,s.reflections.understanding,s.reflections.reflection,s.reflections.application,s.prayer].filter(Boolean).join("\n").trim();return own?[{kind:"chapter" as const,reference:s.passage,text:own}]:[]}),
    ...reviews.flatMap(r=>{const own=[r.takeaway,r.gratitude,r.prayer].filter(Boolean).join("\n").trim();return own?[{kind:"daily_review" as const,reference:r.date,text:own}]:[]}),
    ...verses.flatMap(v=>v.note?.trim()?[{kind:"chapter" as const,reference:v.reference,text:`My verse note: ${v.note.trim()}`}]:[]),
    ...personalPrayers.map(p=>({kind:"prayer" as const,reference:p.createdAt.slice(0,10),text:p.text})),
  ],[studies,reviews,verses,personalPrayers]);
  const remove=(id:string)=>{removeSavedVerse(id);refresh()};
  const ask=async()=>{if(!memoryQuestion.trim())return;setAsking(true);setMemoryMessage("");setMemoryAnswer(null);const res=await askMemory({data:{question:memoryQuestion.trim(),sources:memorySources}});setAsking(false);if(res.ok)setMemoryAnswer(res.answer);else setMemoryMessage(res.error)};
  const addPrayer=()=>{if(addPersonalPrayer(newPrayer)){setNewPrayer("");refresh()}};
  const toggleAnswered=(p:PrayerView)=>{const current=prayerStatuses[p.id];if(isPrayerAnswered(current)){setPrayerAnswered(p.id,false);refresh();return}const note=window.prompt("Optional: how was this prayer answered?",current?.answerNote||"")??"";setPrayerAnswered(p.id,true,note);refresh()};
  return <main className="mx-auto min-h-screen w-full max-w-2xl px-4 pb-28 pt-8 sm:px-6">
    <div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">Your study memory</p><h1 className="mt-1 font-[family-name:var(--font-scripture)] text-4xl font-semibold">Study Journal</h1><p className="mt-2 text-sm text-muted-foreground">Your observations, prayers, highlights and reviews—kept distinct from AI study guidance.</p></div>
    <div className="relative mt-5"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search your study memory…" className="h-10 w-full rounded-xl border bg-background pl-9 pr-3 text-sm"/></div>
    <div className="mt-4 grid grid-cols-5 rounded-xl bg-muted p-1">{(["notes","verses","prayers","reviews","memory"] as Tab[]).map(t=><button key={t} onClick={()=>setTab(t)} className={`rounded-lg px-1 py-2 text-[10px] font-medium capitalize sm:text-[11px] ${tab===t?"bg-background shadow-sm":"text-muted-foreground"}`}>{t}</button>)}</div>

    {tab==="notes"?<section className="mt-5 space-y-3">{filteredStudies.length?filteredStudies.map(s=><Link key={s.passage} to="/read/$passage" params={{passage:s.passage}}><Card className="p-4 transition hover:bg-accent/30"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><NotebookPen className="size-4 text-primary"/><strong>{s.passage}</strong></div>{s.completedAt?<span className="text-[10px] text-primary">Completed</span>:null}</div>{s.intention?<JournalLine label="Before reading" text={s.intention}/>:null}{s.reflections.observation?<JournalLine label="Observe" text={s.reflections.observation}/>:null}{s.reflections.understanding?<JournalLine label="Understand" text={s.reflections.understanding}/>:null}{s.reflections.reflection?<JournalLine label="Reflect" text={s.reflections.reflection}/>:null}{s.reflections.application?<JournalLine label="Apply" text={s.reflections.application}/>:null}{s.prayer?<JournalLine label="Prayer" text={s.prayer}/>:null}</Card></Link>):<Empty text="Your chapter reflections will appear here as you study."/>}</section>:null}

    {tab==="verses"?<section className="mt-5 space-y-3">{filteredVerses.length?filteredVerses.map(item=><Card key={item.id} className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2 text-xs text-muted-foreground">{item.bookmarked?<Bookmark className="size-3.5"/>:<Highlighter className="size-3.5"/>}<span>{item.reference}</span>{item.highlight?<span className="capitalize">· {item.highlight}</span>:null}</div><p className="mt-2 font-[family-name:var(--font-scripture)] leading-relaxed">{item.text}</p>{item.note?<p className="mt-3 rounded-lg bg-muted p-3 text-sm">{item.note}</p>:null}</div><Button variant="ghost" size="icon" onClick={()=>remove(item.id)} aria-label="Delete saved verse"><Trash2 className="size-4"/></Button></div></Card>):<Empty text="Tap a verse in the reader to highlight, bookmark or add a verse note."/>}</section>:null}

    {tab==="prayers"?<section className="mt-5"><Card className="p-4"><div className="flex items-center gap-2"><Heart className="size-4 text-primary"/><h2 className="font-semibold">Prayer journal</h2></div><p className="mt-1 text-xs text-muted-foreground">Chapter and daily-review prayers appear here automatically. You can also add a prayer that is not tied to a reading.</p><Textarea className="mt-3 min-h-20" value={newPrayer} onChange={e=>setNewPrayer(e.target.value)} placeholder="Write a prayer request…"/><Button className="mt-2" size="sm" onClick={addPrayer} disabled={!newPrayer.trim()}><Plus className="mr-1 size-4"/>Add prayer</Button></Card><div className="mt-4 space-y-3">{prayers.length?prayers.map(p=>{const status=prayerStatuses[p.id];const answered=isPrayerAnswered(status);return <Card key={p.id} className={`p-4 ${answered?"opacity-75":""}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2"><Heart className={`size-4 ${answered?"text-green-600":"text-primary"}`}/><p className="text-xs font-semibold text-muted-foreground">{p.reference}</p>{answered?<span className="rounded-full bg-green-500/10 px-2 py-0.5 text-[10px] text-green-700 dark:text-green-300">Answered</span>:null}</div><p className="mt-3 whitespace-pre-wrap text-sm leading-relaxed">{p.text}</p>{status?.answerNote?<div className="mt-3 rounded-lg bg-green-500/10 p-3"><p className="text-[10px] font-semibold uppercase tracking-wide">Answer note</p><p className="mt-1 text-sm">{status.answerNote}</p></div>:null}</div>{p.personal?<Button size="icon" variant="ghost" onClick={()=>{deletePersonalPrayer(p.id);refresh()}} aria-label="Delete prayer"><Trash2 className="size-4"/></Button>:null}</div><Button className="mt-3" size="sm" variant={answered?"outline":"default"} onClick={()=>toggleAnswered(p)}><CheckCircle2 className="mr-1 size-4"/>{answered?"Mark unanswered":"Mark answered"}</Button></Card>}):<Empty text="Prayers you write during study will collect here."/>}</div></section>:null}

    {tab==="reviews"?<section className="mt-5 space-y-3">{filteredReviews.length?filteredReviews.map(r=><Card key={r.date} className="p-4"><p className="text-xs font-semibold uppercase tracking-wide text-primary">{r.date}</p>{r.takeaway?<JournalLine label="Takeaway" text={r.takeaway}/>:null}{r.gratitude?<JournalLine label="Gratitude" text={r.gratitude}/>:null}{r.prayer?<JournalLine label="Prayer" text={r.prayer}/>:null}</Card>):<Empty text="Complete a day's reading and write your Daily Review to build this archive."/>}</section>:null}

    {tab==="memory"?<section className="mt-5"><Card className="p-5"><div className="flex items-center gap-2"><Brain className="size-5 text-primary"/><h2 className="font-semibold">Ask your Study Memory</h2></div><p className="mt-2 text-sm leading-relaxed text-muted-foreground">This AI searches only what <strong>you</strong> wrote in reflections, reviews, verse notes and personal prayers. It does not invent Scripture or personal history.</p><Textarea className="mt-4 min-h-24" value={memoryQuestion} onChange={e=>setMemoryQuestion(e.target.value)} placeholder="What have I been learning about forgiveness? What questions keep coming up? How has my thinking changed?"/><div className="mt-3 flex items-center justify-between gap-3"><span className="text-[11px] text-muted-foreground">{memorySources.length} personal memory entries available</span><Button onClick={ask} disabled={asking||!memoryQuestion.trim()}><Sparkles className="mr-1 size-4"/>{asking?"Searching…":"Search memory"}</Button></div>{memoryMessage?<p className="mt-4 rounded-lg bg-muted p-3 text-sm">{memoryMessage}</p>:null}</Card>{memoryAnswer?<div className="mt-4 space-y-3"><Card className="p-5"><h3 className="font-semibold">From your own study record</h3><p className="mt-3 whitespace-pre-wrap text-sm leading-relaxed">{memoryAnswer.answer}</p></Card><MemoryList title="Sources used" items={memoryAnswer.sources}/><MemoryList title="Patterns in your notes" items={memoryAnswer.patterns}/><MemoryList title="Questions still open" items={memoryAnswer.unresolvedQuestions}/></div>:null}</section>:null}
  </main>;
}
function JournalLine({label,text}:{label:string;text:string}){return <div className="mt-3"><p className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 whitespace-pre-wrap text-sm leading-relaxed">{text}</p></div>}
function Empty({text}:{text:string}){return <Card className="p-8 text-center text-sm text-muted-foreground">{text}</Card>}
function MemoryList({title,items}:{title:string;items:string[]}){if(!items?.length)return null;return <Card className="p-4"><h3 className="text-sm font-semibold">{title}</h3><ul className="mt-2 space-y-2 text-sm text-muted-foreground">{items.map((x,i)=><li key={i}>• {x}</li>)}</ul></Card>}
