import { Link, createFileRoute } from "@tanstack/react-router";
import { Bell, CalendarPlus, Cloud, Download, ListChecks, LogIn, LogOut, RefreshCw, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Switch } from "@/components/ui/switch";
import { DEFAULT_SETTINGS, loadSettings, saveSettings, type AppSettings, type ReadingWidth, type ThemeMode } from "@/lib/app-state";
import { buildStudyCalendarIcs, downloadCalendarIcs } from "@/lib/schedule-export";
import { getCloudUser, sendSignInLink, signOutCloud, syncStudyData } from "@/lib/cloud-sync";
import { clearLocalStudyData, downloadStudyData } from "@/lib/privacy";
import { berlinToday } from "@/lib/schedule";
import { requireSupabase } from "@/lib/supabase";
import type { StudyMode } from "@/lib/study-state";

export const Route=createFileRoute("/settings")({component:SettingsPage});
const tracks=["Law","History","Psalms","Wisdom","Prophets","Gospels","Acts & Epistles"];

function SettingsPage(){
  const [settings,setSettings]=useState<AppSettings>(DEFAULT_SETTINGS);const [account,setAccount]=useState<string|null>(null);const [email,setEmail]=useState("");const [message,setMessage]=useState("");const [syncing,setSyncing]=useState(false);const [notificationState,setNotificationState]=useState("unknown");
  useEffect(()=>{setSettings(loadSettings());getCloudUser().then(u=>setAccount(u?.email??null)).catch(()=>{});if(typeof Notification!=="undefined")setNotificationState(Notification.permission);try{const sb=requireSupabase();const {data}=sb.auth.onAuthStateChange((_e,s)=>setAccount(s?.user.email??null));return()=>data.subscription.unsubscribe()}catch{return}},[]);
  const commit=(patch:Partial<AppSettings>)=>{const next={...settings,...patch};setSettings(next);saveSettings(next);if(typeof document!=="undefined")document.documentElement.dataset["theme"]=next.theme};
  const toggleTrack=(track:string)=>commit({activeTracks:settings.activeTracks.includes(track)?settings.activeTracks.filter(x=>x!==track):[...settings.activeTracks,track]});
  const requestLink=async()=>{if(!email.trim())return;setMessage("Sending sign-in link…");try{await sendSignInLink(email.trim());setMessage("Check your email for the secure sign-in link.")}catch(e){setMessage(e instanceof Error?e.message:"Unable to send sign-in link.")}};
  const sync=async()=>{setSyncing(true);setMessage("");try{await syncStudyData();setSettings(loadSettings());setMessage("Cloud sync complete for supported settings, reading progress and study memory.")}catch(e){setMessage(e instanceof Error?e.message:"Cloud sync failed.")}finally{setSyncing(false)}};
  const logout=async()=>{try{await signOutCloud();setAccount(null);setMessage("Signed out. Local study data remains on this device.")}catch(e){setMessage(e instanceof Error?e.message:"Sign out failed.")}};
  const exportCalendar=()=>{const ics=buildStudyCalendarIcs({startDate:berlinToday(),days:365,time:settings.reminderTime,timezone:settings.timezone,chaptersPerDay:settings.chaptersPerDay,activeTracks:settings.activeTracks});downloadCalendarIcs("daily-bible-study-plan.ics",ics);setMessage("365-day study calendar created. Import the .ics file into your calendar app to receive reliable calendar reminders.")};
  const askNotifications=async()=>{if(typeof Notification==="undefined"){setMessage("This browser does not support web notifications.");return}const permission=await Notification.requestPermission();setNotificationState(permission);setMessage(permission==="granted"?"Notification permission granted. Calendar export remains the reliable way to schedule reminders when the app is closed.":"Notification permission was not granted.")};
  const clearData=()=>{if(!window.confirm("Delete all Bible-study data stored locally on this device? Export it first if you may want it later."))return;clearLocalStudyData();setSettings(DEFAULT_SETTINGS);setMessage("Local study data was cleared. Cloud data, if any, was not deleted.")};
  return <main className="mx-auto min-h-screen w-full max-w-2xl px-4 pb-28 pt-8 sm:px-6">
    <p className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">Make study yours</p><h1 className="mt-1 font-[family-name:var(--font-scripture)] text-4xl font-semibold">Settings</h1>
    <div className="mt-6 space-y-4">
      <Card className="p-5"><h2 className="font-semibold">Study experience</h2><p className="mt-1 text-xs text-muted-foreground">Choose how much guidance you want. “Just read” keeps the experience Scripture-first.</p><div className="mt-4 grid grid-cols-2 gap-2">{(["read","quick","standard","deep"] as StudyMode[]).map(mode=><button key={mode} onClick={()=>commit({studyMode:mode})} className={`rounded-xl border p-3 text-left ${settings.studyMode===mode?"border-primary bg-primary/5":""}`}><p className="text-sm font-medium capitalize">{mode==="read"?"Just read":`${mode} study`}</p><p className="mt-1 text-[11px] text-muted-foreground">{mode==="read"?"Scripture with notes":mode==="quick"?"~10 min/chapter":mode==="standard"?"~18 min/chapter":"~32 min/chapter"}</p></button>)}</div></Card>

      <Card className="p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">Reading plan</h2><p className="mt-1 text-xs text-muted-foreground">Personalize workload without changing the canonical seven-track sequence.</p></div><Link to="/plans"><Button variant="outline" size="sm"><ListChecks className="mr-1 size-4"/>Templates</Button></Link></div><div className="mt-4 flex items-center justify-between"><div><p className="text-sm font-medium">Chapters per day</p><p className="text-xs text-muted-foreground">1–7 from the active tracks</p></div><strong className="text-xl">{settings.chaptersPerDay}</strong></div><input className="mt-3 w-full" type="range" min={1} max={7} value={settings.chaptersPerDay} onChange={e=>commit({chaptersPerDay:Number(e.target.value)})}/><div className="mt-4 flex flex-wrap gap-2">{tracks.map(track=><button key={track} onClick={()=>toggleTrack(track)} className={`rounded-full border px-3 py-1.5 text-xs ${settings.activeTracks.includes(track)?"bg-primary text-primary-foreground":"bg-background text-muted-foreground"}`}>{track}</button>)}</div></Card>

      <Card className="p-5"><h2 className="font-semibold">Reader</h2><label className="mt-4 block text-sm font-medium">Theme</label><select value={settings.theme} onChange={e=>commit({theme:e.target.value as ThemeMode})} className="mt-2 w-full rounded-lg border bg-background p-2 text-sm"><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option><option value="sepia">Sepia</option></select><label className="mt-4 block text-sm font-medium">Reading width</label><select value={settings.readingWidth} onChange={e=>commit({readingWidth:e.target.value as ReadingWidth})} className="mt-2 w-full rounded-lg border bg-background p-2 text-sm"><option value="narrow">Narrow — focused</option><option value="comfortable">Comfortable</option><option value="wide">Wide</option></select><div className="mt-4 flex justify-between"><label className="text-sm font-medium">Scripture font size</label><span className="text-sm text-muted-foreground">{settings.fontSize}px</span></div><input className="mt-2 w-full" type="range" min={16} max={32} value={settings.fontSize} onChange={e=>commit({fontSize:Number(e.target.value)})}/><div className="mt-4 flex justify-between"><label className="text-sm font-medium">Line spacing</label><span className="text-sm text-muted-foreground">{settings.lineHeight.toFixed(1)}</span></div><input className="mt-2 w-full" type="range" min={1.4} max={2.5} step={0.1} value={settings.lineHeight} onChange={e=>commit({lineHeight:Number(e.target.value)})}/><SettingSwitch label="Show verse numbers" checked={settings.showVerseNumbers} onChange={v=>commit({showVerseNumbers:v})}/></Card>

      <Card className="p-5"><h2 className="font-semibold">Audio</h2><div className="mt-4 flex items-center justify-between"><label className="text-sm font-medium">Read-aloud speed</label><select className="rounded-lg border bg-background p-2 text-sm" value={settings.audioRate} onChange={e=>commit({audioRate:Number(e.target.value)})}>{[0.75,1,1.25,1.5,2].map(v=><option key={v} value={v}>{v}×</option>)}</select></div><SettingSwitch label="Auto-scroll with read aloud" checked={settings.autoScroll} onChange={v=>commit({autoScroll:v})}/><p className="mt-3 text-xs text-muted-foreground">Read aloud uses the device/browser speech engine over Scripture retrieved from YouVersion. It does not create or distribute separate Bible audio files.</p></Card>

      <Card className="p-5"><div className="flex items-center gap-2"><Bell className="size-4 text-primary"/><h2 className="font-semibold">Study schedule & reminders</h2></div><div className="mt-4 flex items-center justify-between"><div><p className="text-sm font-medium">Morning study</p><p className="text-xs text-muted-foreground">Preferred start time</p></div><Switch checked={settings.reminderEnabled} onCheckedChange={v=>commit({reminderEnabled:v})}/></div><input className="mt-3 w-full rounded-lg border bg-background p-2 text-sm" type="time" value={settings.reminderTime} onChange={e=>commit({reminderTime:e.target.value})}/><div className="mt-5 flex items-center justify-between"><div><p className="text-sm font-medium">Gentle evening follow-up</p><p className="text-xs text-muted-foreground">Useful when today's study is unfinished</p></div><Switch checked={settings.eveningReminderEnabled} onCheckedChange={v=>commit({eveningReminderEnabled:v})}/></div><input className="mt-3 w-full rounded-lg border bg-background p-2 text-sm" type="time" value={settings.eveningReminderTime} onChange={e=>commit({eveningReminderTime:e.target.value})}/><label className="mt-4 block text-sm font-medium">Timezone</label><input className="mt-2 w-full rounded-lg border bg-background p-2 text-sm" value={settings.timezone} onChange={e=>commit({timezone:e.target.value})}/><div className="mt-4 grid gap-2 sm:grid-cols-2"><Button variant="outline" onClick={exportCalendar}><CalendarPlus className="mr-2 size-4"/>Export 365-day calendar</Button><Button variant="outline" onClick={askNotifications}><Bell className="mr-2 size-4"/>Browser permission: {notificationState}</Button></div><p className="mt-3 text-xs leading-relaxed text-muted-foreground">The calendar export creates actual dated study events with your selected time and readings. Browser notification permission alone cannot guarantee background reminders when this web app is closed; true push delivery requires a push service.</p></Card>

      <Card className="p-5"><div className="flex items-center gap-2"><Cloud className="size-4 text-primary"/><h2 className="font-semibold">Account & cloud sync</h2></div>{account?<><p className="mt-2 text-xs text-muted-foreground">Signed in as {account}. Supported private study data can sync across devices when the cloud schema is available.</p><div className="mt-4 flex gap-2"><Button size="sm" onClick={sync} disabled={syncing}><RefreshCw className={`mr-1 size-3.5 ${syncing?"animate-spin":""}`}/>{syncing?"Syncing…":"Sync now"}</Button><Button size="sm" variant="outline" onClick={logout}><LogOut className="mr-1 size-3.5"/>Sign out</Button></div></>:<><p className="mt-2 text-xs text-muted-foreground">Sign in with an email link to sync supported study data between devices. Anonymous local study remains available.</p><div className="mt-4 flex gap-2"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email address" className="min-w-0 flex-1 rounded-lg border bg-background px-3 text-sm"/><Button size="sm" onClick={requestLink}><LogIn className="mr-1 size-3.5"/>Email link</Button></div></>}{message?<p className="mt-3 rounded-lg bg-muted p-3 text-xs">{message}</p>:null}</Card>

      <Card className="p-5"><h2 className="font-semibold">Privacy & your data</h2><p className="mt-2 text-xs leading-relaxed text-muted-foreground">Scripture comes from YouVersion. Your local reflections, notes, highlights, progress and settings stay on this device unless you explicitly use cloud sync or an AI study feature. Study Memory sends only your authored notes selected for that question—not saved Bible text.</p><div className="mt-4 grid gap-2 sm:grid-cols-2"><Button variant="outline" onClick={downloadStudyData}><Download className="mr-2 size-4"/>Export my local data</Button><Button variant="outline" className="text-destructive" onClick={clearData}><Trash2 className="mr-2 size-4"/>Clear local study data</Button></div></Card>
    </div>
  </main>;
}
function SettingSwitch({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <div className="mt-4 flex items-center justify-between"><label className="text-sm font-medium">{label}</label><Switch checked={checked} onCheckedChange={onChange}/></div>}
