/* eslint-disable */
// @ts-nocheck
// This file is generated by TanStack Router and will be refreshed on the next build.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadPassageRouteImport } from './routes/read.$passage'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({ id:'/', path:'/', getParentRoute:()=>rootRouteImport } as any)
const ReadPassageRoute = ReadPassageRouteImport.update({ id:'/read/$passage', path:'/read/$passage', getParentRoute:()=>rootRouteImport } as any)
const CalendarRoute = CalendarRouteImport.update({ id:'/calendar', path:'/calendar', getParentRoute:()=>rootRouteImport } as any)
const PlansRoute = PlansRouteImport.update({ id:'/plans', path:'/plans', getParentRoute:()=>rootRouteImport } as any)
const SavedRoute = SavedRouteImport.update({ id:'/saved', path:'/saved', getParentRoute:()=>rootRouteImport } as any)
const CommunityRoute = CommunityRouteImport.update({ id:'/community', path:'/community', getParentRoute:()=>rootRouteImport } as any)
const SettingsRoute = SettingsRouteImport.update({ id:'/settings', path:'/settings', getParentRoute:()=>rootRouteImport } as any)

export interface FileRoutesByFullPath { '/':typeof IndexRoute; '/read/$passage':typeof ReadPassageRoute; '/calendar':typeof CalendarRoute; '/plans':typeof PlansRoute; '/saved':typeof SavedRoute; '/community':typeof CommunityRoute; '/settings':typeof SettingsRoute }
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById { __root__:typeof rootRouteImport; '/':typeof IndexRoute; '/read/$passage':typeof ReadPassageRoute; '/calendar':typeof CalendarRoute; '/plans':typeof PlansRoute; '/saved':typeof SavedRoute; '/community':typeof CommunityRoute; '/settings':typeof SettingsRoute }
export interface FileRouteTypes { fileRoutesByFullPath:FileRoutesByFullPath; fullPaths:'/'|'/read/$passage'|'/calendar'|'/plans'|'/saved'|'/community'|'/settings'; fileRoutesByTo:FileRoutesByTo; to:'/'|'/read/$passage'|'/calendar'|'/plans'|'/saved'|'/community'|'/settings'; id:'__root__'|'/'|'/read/$passage'|'/calendar'|'/plans'|'/saved'|'/community'|'/settings'; fileRoutesById:FileRoutesById }
export interface RootRouteChildren { IndexRoute:typeof IndexRoute; ReadPassageRoute:typeof ReadPassageRoute; CalendarRoute:typeof CalendarRoute; PlansRoute:typeof PlansRoute; SavedRoute:typeof SavedRoute; CommunityRoute:typeof CommunityRoute; SettingsRoute:typeof SettingsRoute }

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id:'/'; path:'/'; fullPath:'/'; preLoaderRoute:typeof IndexRouteImport; parentRoute:typeof rootRouteImport }
    '/read/$passage': { id:'/read/$passage'; path:'/read/$passage'; fullPath:'/read/$passage'; preLoaderRoute:typeof ReadPassageRouteImport; parentRoute:typeof rootRouteImport }
    '/calendar': { id:'/calendar'; path:'/calendar'; fullPath:'/calendar'; preLoaderRoute:typeof CalendarRouteImport; parentRoute:typeof rootRouteImport }
    '/plans': { id:'/plans'; path:'/plans'; fullPath:'/plans'; preLoaderRoute:typeof PlansRouteImport; parentRoute:typeof rootRouteImport }
    '/saved': { id:'/saved'; path:'/saved'; fullPath:'/saved'; preLoaderRoute:typeof SavedRouteImport; parentRoute:typeof rootRouteImport }
    '/community': { id:'/community'; path:'/community'; fullPath:'/community'; preLoaderRoute:typeof CommunityRouteImport; parentRoute:typeof rootRouteImport }
    '/settings': { id:'/settings'; path:'/settings'; fullPath:'/settings'; preLoaderRoute:typeof SettingsRouteImport; parentRoute:typeof rootRouteImport }
  }
}

const rootRouteChildren:RootRouteChildren={IndexRoute,ReadPassageRoute,CalendarRoute,PlansRoute,SavedRoute,CommunityRoute,SettingsRoute}
export const routeTree=rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' { interface Register { server:Awaited<ReturnType<typeof startInstance>> } }
declare module '@tanstack/react-router' { interface Register { router:ReturnType<typeof getRouter> } }
