/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiGenerateStudyImageRouteImport } from './routes/api/generate-study-image'
import { Route as ReadPassageRouteImport } from './routes/read.$passage'
import { Route as ApiStudyVideoAdvanceRouteImport } from './routes/api/study-video/advance'
import { Route as ApiStudyVideoRetryRouteImport } from './routes/api/study-video/retry'
import { Route as ApiStudyVideoSequenceStartRouteImport } from './routes/api/study-video/sequence-start'
import { Route as ApiStudyVideoStartRouteImport } from './routes/api/study-video/start'
import { Route as ApiStudyVideoStatusRouteImport } from './routes/api/study-video/status'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateStudyImageRoute = ApiGenerateStudyImageRouteImport.update({
  id: '/api/generate-study-image',
  path: '/api/generate-study-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadPassageRoute = ReadPassageRouteImport.update({
  id: '/read/$passage',
  path: '/read/$passage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudyVideoAdvanceRoute = ApiStudyVideoAdvanceRouteImport.update({
  id: '/api/study-video/advance',
  path: '/api/study-video/advance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudyVideoRetryRoute = ApiStudyVideoRetryRouteImport.update({
  id: '/api/study-video/retry',
  path: '/api/study-video/retry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudyVideoSequenceStartRoute =
  ApiStudyVideoSequenceStartRouteImport.update({
    id: '/api/study-video/sequence-start',
    path: '/api/study-video/sequence-start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStudyVideoStartRoute = ApiStudyVideoStartRouteImport.update({
  id: '/api/study-video/start',
  path: '/api/study-video/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudyVideoStatusRoute = ApiStudyVideoStatusRouteImport.update({
  id: '/api/study-video/status',
  path: '/api/study-video/status',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/community': typeof CommunityRoute
  '/plans': typeof PlansRoute
  '/progress': typeof ProgressRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/api/generate-study-image': typeof ApiGenerateStudyImageRoute
  '/read/$passage': typeof ReadPassageRoute
  '/api/study-video/advance': typeof ApiStudyVideoAdvanceRoute
  '/api/study-video/retry': typeof ApiStudyVideoRetryRoute
  '/api/study-video/sequence-start': typeof ApiStudyVideoSequenceStartRoute
  '/api/study-video/start': typeof ApiStudyVideoStartRoute
  '/api/study-video/status': typeof ApiStudyVideoStatusRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/community': typeof CommunityRoute
  '/plans': typeof PlansRoute
  '/progress': typeof ProgressRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/api/generate-study-image': typeof ApiGenerateStudyImageRoute
  '/read/$passage': typeof ReadPassageRoute
  '/api/study-video/advance': typeof ApiStudyVideoAdvanceRoute
  '/api/study-video/retry': typeof ApiStudyVideoRetryRoute
  '/api/study-video/sequence-start': typeof ApiStudyVideoSequenceStartRoute
  '/api/study-video/start': typeof ApiStudyVideoStartRoute
  '/api/study-video/status': typeof ApiStudyVideoStatusRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/community': typeof CommunityRoute
  '/plans': typeof PlansRoute
  '/progress': typeof ProgressRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/api/generate-study-image': typeof ApiGenerateStudyImageRoute
  '/read/$passage': typeof ReadPassageRoute
  '/api/study-video/advance': typeof ApiStudyVideoAdvanceRoute
  '/api/study-video/retry': typeof ApiStudyVideoRetryRoute
  '/api/study-video/sequence-start': typeof ApiStudyVideoSequenceStartRoute
  '/api/study-video/start': typeof ApiStudyVideoStartRoute
  '/api/study-video/status': typeof ApiStudyVideoStatusRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/community'
    | '/plans'
    | '/progress'
    | '/saved'
    | '/settings'
    | '/api/generate-study-image'
    | '/read/$passage'
    | '/api/study-video/advance'
    | '/api/study-video/retry'
    | '/api/study-video/sequence-start'
    | '/api/study-video/start'
    | '/api/study-video/status'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/community'
    | '/plans'
    | '/progress'
    | '/saved'
    | '/settings'
    | '/api/generate-study-image'
    | '/read/$passage'
    | '/api/study-video/advance'
    | '/api/study-video/retry'
    | '/api/study-video/sequence-start'
    | '/api/study-video/start'
    | '/api/study-video/status'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/community'
    | '/plans'
    | '/progress'
    | '/saved'
    | '/settings'
    | '/api/generate-study-image'
    | '/read/$passage'
    | '/api/study-video/advance'
    | '/api/study-video/retry'
    | '/api/study-video/sequence-start'
    | '/api/study-video/start'
    | '/api/study-video/status'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  CommunityRoute: typeof CommunityRoute
  PlansRoute: typeof PlansRoute
  ProgressRoute: typeof ProgressRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  ApiGenerateStudyImageRoute: typeof ApiGenerateStudyImageRoute
  ReadPassageRoute: typeof ReadPassageRoute
  ApiStudyVideoAdvanceRoute: typeof ApiStudyVideoAdvanceRoute
  ApiStudyVideoRetryRoute: typeof ApiStudyVideoRetryRoute
  ApiStudyVideoSequenceStartRoute: typeof ApiStudyVideoSequenceStartRoute
  ApiStudyVideoStartRoute: typeof ApiStudyVideoStartRoute
  ApiStudyVideoStatusRoute: typeof ApiStudyVideoStatusRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-study-image': {
      id: '/api/generate-study-image'
      path: '/api/generate-study-image'
      fullPath: '/api/generate-study-image'
      preLoaderRoute: typeof ApiGenerateStudyImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$passage': {
      id: '/read/$passage'
      path: '/read/$passage'
      fullPath: '/read/$passage'
      preLoaderRoute: typeof ReadPassageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study-video/advance': {
      id: '/api/study-video/advance'
      path: '/api/study-video/advance'
      fullPath: '/api/study-video/advance'
      preLoaderRoute: typeof ApiStudyVideoAdvanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study-video/retry': {
      id: '/api/study-video/retry'
      path: '/api/study-video/retry'
      fullPath: '/api/study-video/retry'
      preLoaderRoute: typeof ApiStudyVideoRetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study-video/sequence-start': {
      id: '/api/study-video/sequence-start'
      path: '/api/study-video/sequence-start'
      fullPath: '/api/study-video/sequence-start'
      preLoaderRoute: typeof ApiStudyVideoSequenceStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study-video/start': {
      id: '/api/study-video/start'
      path: '/api/study-video/start'
      fullPath: '/api/study-video/start'
      preLoaderRoute: typeof ApiStudyVideoStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study-video/status': {
      id: '/api/study-video/status'
      path: '/api/study-video/status'
      fullPath: '/api/study-video/status'
      preLoaderRoute: typeof ApiStudyVideoStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  CommunityRoute: CommunityRoute,
  PlansRoute: PlansRoute,
  ProgressRoute: ProgressRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  ApiGenerateStudyImageRoute: ApiGenerateStudyImageRoute,
  ReadPassageRoute: ReadPassageRoute,
  ApiStudyVideoAdvanceRoute: ApiStudyVideoAdvanceRoute,
  ApiStudyVideoRetryRoute: ApiStudyVideoRetryRoute,
  ApiStudyVideoSequenceStartRoute: ApiStudyVideoSequenceStartRoute,
  ApiStudyVideoStartRoute: ApiStudyVideoStartRoute,
  ApiStudyVideoStatusRoute: ApiStudyVideoStatusRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
